Update check-update.yml

diff --git a/.github/workflows/check-update.yml b/.github/workflows/check-update.yml
--- a/.github/workflows/check-update.yml
+++ b/.github/workflows/check-update.yml
@@ -14,5 +14,6 @@ jobs:
         run: |
           XMAKE_LATEST=$(curl -fs https://api.github.com/repos/xmake-io/xmake/releases/latest | grep -E "\"tag_name\":\s?\"v[0-9.]+\"" | grep -Eo "[0-9.]+")
           if [ "$XMAKE_LATEST" != "3.0.0" ]; then
-            echo "::warning:: Xmake has update: $XMAKE_LATEST"
+            echo "::error:: Xmake has update: $XMAKE_LATEST"
+            exit 1
           fi
